repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
    -   id: mypy
        exclude: migrations
        args: [--warn-unused-configs, --disallow-any-generics, --disallow-untyped-calls, --disallow-untyped-defs,
               --disallow-incomplete-defs, --check-untyped-defs, --warn-redundant-casts, --warn-unused-ignores,
               --warn-return-any, --no-implicit-reexport, --strict-equality, --extra-checks, --ignore-missing-imports]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.2
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
