""" """

from yoyo import step

__depends__ = {}

steps = [
    step("""
        CREATE TABLE user_roles (
            id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            code varchar not null,
            description text null 
        )
    """),
    step("""
        CREATE TABLE users (
            id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            created_at timestamp WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
            updated_at timestamp WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
            username varchar(20) unique not null,
            password_hashed varchar not null,
            revoked bool default false
        )
"""),
    step("""
        CREATE TABLE roles_to_users (
            id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            user_id integer not null references users ON UPDATE CASCADE ON DELETE CASCADE,
            role_id integer not null references user_roles ON UPDATE CASCADE ON DELETE CASCADE
        )
    """),
    step("""
        CREATE TABLE devices (
            id uuid default gen_random_uuid() PRIMARY KEY,
            user_id integer not null references users,
            name varchar,
            revoked bool default false,
            last_activity timestamp
        )
    """),
    step("""
        INSERT INTO user_roles (code, description) 
        VALUES
            ('admin', 'Можно всё'),
            ('user', 'Пользователь системы') 
        """),
]
