"""

"""

from yoyo import step

__depends__ = {}

steps = [
    step("""
    CREATE TABLE user_roles (
        id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        code varchar not null,
        description text null 
    )
    """),
    step("""
    CREATE TABLE users (
        id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        created_at timestamp WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        updated_at timestamp WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        username varchar(20) unique not null,
        password_hashed varchar not null,
        disabled bool default false
    )
"""),
    step("""
    CREATE TABLE user_roles (
        id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        user_id integer not null references users,
        role_id integer not null references user_roles
    )
    """)
]
